### ISSUE TITLE
This is a great package (not an issue).

### ISSUE THREAD

**Issue by jbaileyh** [kaerosen/mastersproject#1]
Hi @kaerosen, just stumbled across your package and it looks great. For reference, there is another similar one [here](https://github.com/jbaileyh/geogrid). If you ever think it's useful to merge these, please let me know as I don't currently have the time needed to regularly update `{geogrid}`. Glad to find more keen mappers!

**Comment by kaerosen** [comment]
Hi @jbaileyh, thanks for reaching out to me! The ``geogrid`` package looks really interesting, but unfortunately, I don't think I'll have time in the near future to merge the packages.
