### ISSUE TITLE
Exporting tiles as a shapefile

### ISSUE THREAD

**Issue by cdrowley** [kaerosen/mastersproject#2]
After having read the "Generating Tile Maps" paper I was relieved to find this repository, great work!

I believe I have generated a useful output but I'm having some difficulty extracting a suitable tilemap from the many_maps function. Is this possible?

**Comment by kaerosen** [comment]
Yes, it is possible! Suppose you have the output of the `many_maps()` function saved as `map_df`, and you want to add the 3rd map shown in the plot generated by the `many_maps()` function to some other data frame `df`. Then you can use the code `df$tile_map <- map_df$map[[3]]` to create a new column in the other data frame representing the selected tile map.
