### ISSUE TITLE
maintain contiguity of lower-level units 

### ISSUE THREAD

**Issue by schmert** [kaerosen/mastersproject#6]
{tilemaps} is a wonderful package. Thanks. I'm trying to use it to create a map of hexagons representing Sweden's 290 municipalities. Each municipality belongs to one of 21 counties, and I would like tiles belonging to the same county to be contiguous. 

Just as an example, the attached map shows a typical municipality tilemap, with the municipalities belonging to Stockholm county in red.  Is there any way to force generate_map to keep them together? 

![SWE-tiles](https://github.com/kaerosen/tilemaps/assets/6287005/44c15176-229d-4980-aba3-c035e12b5aff)

**Comment by kaerosen** [comment]
Currently the generate_map function doesn’t support any hierarchical structure of the data. My best suggestion for ensuring that all municipalities within a county are contiguous would be to generate a tile map for each county, and then compile all the maps together.

**Comment by schmert** [comment]
Thanks. That's what I suspected.  I'll see what I can do with the one-county-at-a-time approach.  Different sizes of tiles will be a problem.

Here's the first attempt:
![image](https://github.com/kaerosen/tilemaps/assets/6287005/1fc8ea3c-2f8f-4cae-ae16-77808afde31b)
